version: '3'
services:
  pathology-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
        - JWT_SECRET=anything
        - LOCAL=true
    volumes:
      - ./:/app
      - /app/.next    
    ports:
      - "3000:3000"